sudo: true
language: go
go:
  - "1.10.x"
  - "1.11.x"
  - master
# NOTE: Create fake `vagrant` binary
install:
  - sudo apt update
  - sudo apt install -y vagrant
  - which vagrant
script: go test -v ./...
