sudo: false
language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
# NOTE: Create fake `vagrant` binary
before_script:
  - sudo apt update
  - sudo apt install -y vagrant
  - which vagrant
script:
  - go test -v ./...
